package by.kostyl.booking.ui;

import java.time.LocalDate;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.Binder;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

import by.kostyl.booking.entity.Hotel;
import by.kostyl.booking.entity.HotelCategory;
import by.kostyl.booking.service.HotelService;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */

public class HotelForm extends FormLayout {
	private MyUI ui;
	private Hotel hotel;
	private HotelService hotelService = HotelService.getInstance();
	private TextField name = new TextField("name");
	private TextArea description = new TextArea("description");
	private TextField address = new TextField("adress");

	private TextField rating = new TextField("rating");
	private TextField url = new TextField("link to booking");

	private DateField operatesFrom = new DateField("from");

	private NativeSelect<HotelCategory> category = new NativeSelect<>("category");

	private Button saveBtn = new Button("Save");
	private Button deleteBtn = new Button("Delete");
	private Binder<Hotel> hotelBinder = new Binder(Hotel.class);

	public HotelForm(MyUI ui) {
		this.ui = ui;
		setSizeUndefined();
		HorizontalLayout buttons = new HorizontalLayout(saveBtn, deleteBtn);
		addComponents(name, address, rating, url, operatesFrom, category, description, buttons);
		category.setItems(HotelCategory.values());
		deleteBtn.addClickListener(e -> deleteHotel());
		hotelBinder.bindInstanceFields(this);
		saveBtn.addClickListener(e -> saveHotel());
	}

	public Hotel getHotel() {
		return hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
		System.out.println(hotel);
		hotelBinder.setBean(hotel);
		deleteBtn.setVisible(hotel.isPersisted());
		setVisible(true);
		name.selectAll();
	}

	public void deleteHotel() {
		hotelService.delete(hotel);
		this.ui.updateHotels("");
		setVisible(false);

	}

	public void saveHotel() {
		hotelService.save(hotel);
		this.ui.updateHotels("");
		setVisible(false);

	}

}
